# Generated by Django 3.2.1 on 2021-05-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('semister', models.CharField(max_length=5)),
                ('branch', models.CharField(max_length=5)),
                ('sub1', models.CharField(max_length=200)),
                ('sub2', models.CharField(max_length=200)),
                ('sub3', models.CharField(max_length=200)),
                ('sub4', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=5)),
                ('semister', models.CharField(max_length=5)),
                ('topic1', models.CharField(max_length=200)),
                ('topic2', models.CharField(max_length=200)),
                ('topic3', models.CharField(max_length=200)),
                ('topic4', models.CharField(max_length=200)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.courses')),
            ],
        ),
    ]
