# Generated by Django 3.2.1 on 2021-05-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='subject',
        ),
        migrations.AlterField(
            model_name='course_details',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
