# Generated by Django 3.2.1 on 2021-05-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20210519_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_details',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='course_details',
            name='semister',
        ),
    ]
