# Generated by Django 3.2.1 on 2021-05-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20210519_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='stud_details',
            fields=[
                ('semister', models.CharField(max_length=5)),
                ('branch', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
